---
title: "Fantasy Football"
author: "Luke Thomas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval = FALSE}
library(usethis)
use_git_config(user.name= "LukeT33", user.email="ldt19@duke.edu")
```

```{r setup, include = FALSE}
library(tidyverse)
```

```{r sites}
targets <- read_html("https://www.fantasypros.com/nfl/reports/targets/")
pointsallowed <- read_html("https://www.fantasypros.com/nfl/points-allowed.php")
```

```{r teams}
teams <- pointsallowed %>%
  html_nodes("#data a") %>%
  html_text()
```

```{r qb-points-allowed}
qb_points_allowed <- pointsallowed %>%
  html_nodes(".center:nth-child(3) span") %>%
  html_text()
```

```{r rb-points-allowed}
rb_points_allowed <- pointsallowed %>%
  html_nodes(".center:nth-child(5) span") %>%
  html_text
```

```{r}
fantasy_points_allowed <-tibble(
  team = teams,
  QB_Points_Allowed = qb_points_allowed,
  RB_Points_Allowed = rb_points_allowed
)

fantasy_points_allowed %>%
  arrange(RB_Points_Allowed)
```











